require 'active_support/all'
require 'rack/parser'
require 'sinatra'
require 'sinatra/json'

require 'rgb'
require 'rgba'
require 'rgb_a_utils'
require 'rgb_value_parser'
require 'string_validator'
require 'string_validator_api'
